---
# Source: nginx-ingress/templates/controller-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.6.13
    component: "controller"
    heritage: Tiller
    release: release-name
  name: release-name-nginx-ingress-controller
data:
  enable-vts-status: "false"
